CREATE TABLE doctors (
    id varchar(100) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    address VARCHAR(255),
    phone VARCHAR(255) NOT NULL,
    birth DATE,
    jk VARCHAR(255),
    nik VARCHAR(255),
    image_ktp VARCHAR(255),
    spesialisasi VARCHAR(255),
    experience VARCHAR(255),
    number_str VARCHAR(255),
    number_sip VARCHAR(255),
    education VARCHAR(255),
    upload_str VARCHAR(255),
    upload_sip VARCHAR(255),
    upload_sertifikasi VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
)